# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- jenkins

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '23.1'
    checkLatest: true
  env:
    PORT: 8080
    MONGO_URI: mongodb+srv://andypandaan:uEMVUbYqtLwgxeu5@exp-cluster-0.tc1gf.mongodb.net/?retryWrites=true&w=majority&appName=exp-cluster-0
    API_DIR_PATH: /api/routes
- script: |
    npm install -g pnpm
    pnpm run test
  displayName: 'Set up npm and pnpm environment'

- task: PublishTestResults@2
  inputs:  
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'npm install and build'