# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- jenkins

pool:
  vmImage: ubuntu-latest

steps:
- bash: echo $(MONGO_URI)
- task: NodeTool@0
  inputs:
    versionSpec: '23.1'
    checkLatest: true
- script: |
    npm install -g pnpm
    pnpm install
    pnpm run dev
    pnpm run test
  displayName: 'Set up npm and pnpm environment'

- task: PublishTestResults@2
  inputs:  
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'npm install and build'