# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- jenkins

pool:
  vmImage: ubuntu-latest

steps:
- script: echo installing pnpm
  displayName: 'build and test stage'

- script: |

    curl -fsSL https://fnm.vercel.app/install | bash
    source ~/.bashrc
    fnm use --install-if-missing 23
    node -v 
    npm -v
  displayName: 'Run a multi-line script'
