
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB port
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - express_api_network
    volumes:
      - mongodb_data:/data/db  # Volume for persistent data

  app:
    build:
      context: .  # Directory containing the Dockerfile
      dockerfile: dockerfile  # Specify the Dockerfile name if it's not the default
    container_name: express-ts-api
    ports:
      - "8080:8080"  # Expose the app port
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/collections?authSource=admin  # Connection URI
    depends_on:
      - mongodb  # Ensure MongoDB starts before the app
    networks:
      - express_api_network

networks:
  express_api_network:
    driver: bridge  # Create a bridge network

volumes:
  mongodb_data: