
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LOCAL_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${LOCAL_MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - express_api_network
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: express-ts-api
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${LOCAL_MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - express_api_network

networks:
  express_api_network:
    driver: bridge

volumes:
  mongodb_data: